spring:
  data:
    mongodb:
      host: ${db.host:192.168.180.50}
      port: ${db.port:30677}
      database: ${db.database:user}
      auto-index-creation: true
server:
  port: ${port:8080}
logging:
  level:
    root: ${log.level:info}